## 섹션 11. 예외 처리2 - 실습

### 1. 예외 처리 도입1 - 시작
![체크예외도입](https://github.com/somminn/TIL/blob/main/image/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202025-03-14%20%EC%98%A4%ED%9B%84%204.30.22.png?raw=true)
- 예외 처리 도입 전
```
  public String connect() {
        // 연결 실패
        if (connectError) {
            System.out.println(address + " 서버 연결 실패");
            return "connectError";
        }
        // 연결 성공
        System.out.println(address + " 서버 연결 성공");
        return "success";
    }
```
- 예외 처리 도입 
```
 public void connect() throws NetworkClientExceptionV2{
        // 연결 실패
        if (connectError) {
            throw new NetworkClientExceptionV2("connectError", address + " 서버 연결 실패" );
        }
        // 연결 성공
        System.out.println(address + " 서버 연결 성공");
    }
```
- 오류가 발생했을 때 오류코드를 반환하는 것이 아니라 예외를 던진다.
- 예외가 main() 밖으로 던져지면 예외 정보와 스택 트레이스(Stack Trace)를 출력하고 프로그램이 종료된다.


### 2. 예외 처리 도입2 - 예외 복구

```
    try {
        client.connect();
    } catch (NetworkClientExceptionV2 e) {
        System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        return;
    }

    try {
        client.send(data);
    } catch (NetworkClientExceptionV2 e) {
        System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        return;
    }
    client.disconnect();
```

### 3. 예외 처리 도입3 - 정상, 예외 흐름 분리 
```
    try {
        client.connect();
        client.send(data);
        client.disconnect();
    } catch (NetworkClientExceptionV2 e) {
        System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
    }
```

자바의 예외처리 매커니즘과 try, catch 구조 덕분에 정상 흐름은 try 블럭에 모아서 처리하고 예외 흐름은 catch 블럭에 별도로 모아서 처리함


### 4. 예외 처리 도입4 - 리소스 반환 문제

disconnect() 메서드를 꼭 실행하도록 수정해보자.
```
   try {
        client.connect();
        client.send(data);
    } catch (NetworkClientExceptionV2 e) {
        System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
    }                   
    client.disconnect();
```
이 코드의 문제점 : NetworkClientExceptionV2 예외가 아닌 다른 예외가 발생한다면 catch 의 대상이 되지못해 밖으로 던져진다.


### 5. 예외 처리 도입5 - finally
`자바는 어떤 경우라도 반드시 호출되는 finally 기능을 제공한다.`
```
    try { 
        // 정상 흐름
    } catch { 
        // 예외 흐름 
    } finally {
        // 반드시 호출해야 하는 마무리 흐름 
    }
```
- try ~ catch ~ finally 구조는 정상 흐름, 예외 흐름, 마무리 흐름을 제공한다.
- try ~ catch ~ finally 구조의 장점
  - 정상 흐름과 예외 흐름을 분리해서, 코드를 읽기 쉽게 만든다.
  - 사용한 자원을 항상 반환할 수 있도록 보장해준다.

#### 처리할 수 없는 예외와 finally
- 심지어 try, catch 안에서 잡을 수 없는 예외가 발생해도(던져도) finally 는 반드시 호출된다.
- try, catch 안에서 잡을 수 없는 예외가 발생해서, 예외를 밖으로 던지는 경우에도 finally 를 먼저 호출하고 나서 예
    외를 밖으로 던진다.



### 6. 예외 계층1 - 시작
![예외계층화](https://github.com/somminn/TIL/blob/main/image/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202025-03-14%20%EC%98%A4%ED%9B%84%204.30.50.png?raw=true)
예외를 단순히 오류 코드로 분류하는 것이 아니라, 예외를 계층화해서 다양하게 만들면 더 세밀하게 예외를 처리할 수 있다.
- 부모 예외를 잡거나 던지면, 자식 예외도 함께 잡거나 던질 수 있다. 
  - NetworkClientExceptionV3 예외를 잡으면 그 하위인 ConnectExceptionV3,
    SendExceptionV3 예외도 함께 잡을 수 있다.
- 특정 예외를 잡아서 처리하고 싶으면 하위 예외를 잡 아서 처리하면 된다.

#### 예외 분류 후 예외 생성
```
    public void connect() throws ConnectExceptionV3 {
            // 연결 실패
            if (connectError) {
                throw new ConnectExceptionV3(address, address + " 서버 연결 실패" );
            }
            // 연결 성공
            System.out.println(address + " 서버 연결 성공");
        }
    
        public void send(String data) throws SendExceptionV3 {
            // 전송 실패
            if (sendError) {
                throw new SendExceptionV3(data, address + " 서버에 데이터 전송 실패: " );
            }
            // 전송 성공
            System.out.println(address + " 서버에 데이터 전송: " + data);
        }

```
오류 코드로 어떤 문제가 발생했는지 이해하는 것이 아니라 예외 그 자체로 어떤 오류가 발생했는지 알 수 있다.


#### 예외 생성 후 예외 처리
```
    try {
        client.connect();
        client.send(data);
    } catch (ConnectExceptionV3 e) {
        System.out.println("[연결 오류] 주소: " + e.getAddress() + ", 메시지: " + e.getMessage());
    } catch (SendExceptionV3 e) {
        System.out.println("[전송 오류] 전송 데이터: " + e.getSendData() + ", 메시지: " + e.getMessage());
    } finally {
        client.disconnect();
    }
```
예외 클래스를 각각의 예외 상황에 맞추어 만들면, 각 필요에 맞는 예외를 잡아서 처리할 수 있다.


### 7. 예외 계층2 - 활용

```
    try {
        client.connect();
        client.send(data);
    } catch (ConnectExceptionV3 e) {
        System.out.println("[연결 오류] 주소: " + e.getAddress() + ", 메시지: " + e.getMessage());
    } catch (NetworkClientExceptionV3 e) {
        System.out.println("[네트워크 오류] 메시지: " + e.getMessage());
    } catch (Exception e) {
        System.out.println("[알 수 없는 오류] 메시지: " + e.getMessage());
    } finally {
        client.disconnect();
    }
```
`주의 : 예외가 발생했을 때 catch는 순서대로 실행하므로, 더 디테일한 자식을 먼저 잡아야 한다.`
- 연결 오류같은 중요한 에러는 메시지를 명확하게 출력하자 
  - catch (ConnectExceptionV3 e)
- 나머지 네트워크 에러는 동일하게 출력하자
  - catch (NetworkClientExceptionV3 e)
  - NetworkClientExceptionV3 는 다른 네트워크 예외들의 부모 타입이므로 예외를 잡을 수 있다.
- 빈 틈을 막기 위해 모든 예외를 잡아서 처리하자
  - catch (Exception e)
  - Exception 은 모든 예외들의 부모이므로 여기서 모든 예외가 잡힌다.


### 8. 실무 예외 처리 방안1 - 설명
#### 체크 예외 사용 시나리오
![체크 예외 사용 시나리오](https://github.com/somminn/TIL/blob/main/image/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202025-03-14%20%EC%98%A4%ED%9B%84%208.53.31.png?raw=true)
- 처리할 수 없는 예외 : 예외를 잡아서 복구할 수 있는 예외보다 복구할 수 없는 예외가 더 많다.
- 체크 예외의 부담 : 처리할 수 없는 예외는 밖으로 던져야 한다. 체크 예외이므로 throws 에 던질 대상을 일일이 명시해야 한다.
  - 그렇다고 exception 에 던져버리면 다른 체크 예외를 체크할 수 있는 기능이 무효화 된다.

#### 언체크 예외 사용 시나리오
- 본인이 처리할 수 없는 예외들이기 때문에 밖으로 던지는 것이 더 나은 결정이다.
- 만약 일부 언체크 예외를 잡아서 처리할 수 있다면 잡아서 처리하면 된다.


### 9. 실무 예외 처리 방안2 - 구현

### 10.
### 11.













